### ISSUE TITLE
tech review for spectra_generator.md

### ISSUE THREAD

**Issue by jkrick** [nasa-fornax/fornax-demo-notebooks#336]
This notebook needs a tech review.  I think it got a quick check by Troy a while back, but can either @bsipocz or @troyraen please do a tech review?

We don't intend to scale the notebook up, so functions do not need to be modified for efficiency.

**Comment by troyraen** [comment]
When reviewing, see also: #285

**Comment by troyraen** [comment]
Tracking what's done and still to-do from [Tech Review Checklist](https://github.com/nasa-fornax/fornax-documentation/blob/main/notebook_review_process.md#tech-review-checklist)
- [x] Documentation
    - Done in #356 
- [ ] Notebook execution, error handling, etc.
    - Notebook runs to completion but throws one `FileNotFoundError` and a few warnings. I'll open a PR to address the error and maybe the warnings (need to look closer at those).
- [x] Efficiency (skipping this)
- [ ] Cleanup
    - Mostly done in #354. I'll do another small PR to get the rest.

**Comment by troyraen** [comment]
Everything is done here except for work on the JWST function (#360). Those problems seem to be server-side and we are working with MAST to get them sorted out.

**Comment by troyraen** [comment]
All items from the tech review checklist are done. Issues with the JWST function have been worked out, at least enough so that it returns data and doesn't raise errors or warnings. Note that some of the files that were previously available no longer exist in the MAST archive (see https://github.com/nasa-fornax/fornax-demo-notebooks/pull/360#issuecomment-2524193964).

@bsipocz Do you want this issue to stay open until the rendering issues get worked out?

**Comment by bsipocz** [comment]
No, we can handle the rendering as a separate question and anything content related coming up in it can have its own issue (e.g. the timeout issue, or anything else that comes up)
